# Generated by Django 4.2.13 on 2024-06-26 08:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_collaboraterequest_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
